- type: custom-api
  title: Media Releases
  cache: 10m
  frameless: true
  options:
    interval: 30
    aspect-ratio: portrait
    radarr-url: https://rad.${BASE_HOST}
    radarr-key: ${RADARR_KEY}
    sonarr-url: https://son.${BASE_HOST}
    sonarr-key: ${SONARR_KEY}
  template: |
    {{ $aspectRatio := .Options.StringOr "aspect-ratio" "portrait" }}
    {{ $intervalH := .Options.IntOr "interval" 30 | mul 24 }}
    {{ $radarrUrl := .Options.StringOr "radarr-url" "" }}
    {{ $sonarrUrl := .Options.StringOr "sonarr-url" "" }}
    {{ $radarrKey := .Options.StringOr "radarr-key" "" }}
    {{ $sonarrKey := .Options.StringOr "sonarr-key" "" }}

    {{ $now := now | formatTime "2006-01-02T15:04:05" }}
    {{ $endDate := offsetNow (printf "+%dh" $intervalH) | formatTime "2006-01-02T15:04:05" }}

    {{ $radarrReq := printf "%s/api/v3/calendar?start=%s&end=%s" $radarrUrl $now $endDate }}
    {{ $sonarrReq := printf "%s/api/v3/calendar?includeSeries=true&start=%s&end=%s" $sonarrUrl $now $endDate }}

    {{ $radarrData := newRequest $radarrReq
      | withHeader "Accept" "application/json"
      | withHeader "X-Api-Key" $radarrKey
      | getResponse }}

    {{ $sonarrData := newRequest $sonarrReq
      | withHeader "Accept" "application/json"
      | withHeader "X-Api-Key" $sonarrKey
      | getResponse }}

    {{ if and (eq $radarrData.Response.StatusCode 200) (eq $sonarrData.Response.StatusCode 200) }}
    <div class="carousel-container show-right-cutoff">
      <div class="cards-horizontal carousel-items-container">
        {{/* Display movies first */}}
        {{ range $radarrData.JSON.Array "" | sortByTime "releaseDate" "rfc3339" "asc" }}
          {{ $title := .String "title" }}
          {{ $coverUrl := printf "%s/api/v3/mediacover/%s/poster-500.jpg?apikey=%s" $radarrUrl (.String "id") $radarrKey }}
          {{ $link := printf "%s/movie/%s" $radarrUrl (.String "titleSlug") }}
          
          {{ $releaseType := "Release" }}
          {{ $selectedDate := .String "releaseDate" }}
          
          {{ $inCinemas := .String "inCinemas" }}
          {{ $digitalRelease := .String "digitalRelease" }}
          {{ $physicalRelease := .String "physicalRelease" }}
          
          {{/* Find the next upcoming release */}}
          {{ if ne $physicalRelease "" }}
            {{ if gt $physicalRelease $now }}
              {{ $releaseType = "Physical" }}
              {{ $selectedDate = $physicalRelease }}
            {{ end }}
          {{ end }}
          
          {{ if ne $digitalRelease "" }}
            {{ if gt $digitalRelease $now }}
              {{ if or (eq $selectedDate .String "releaseDate") (lt $digitalRelease $selectedDate) }}
                {{ $releaseType = "Digital" }}
                {{ $selectedDate = $digitalRelease }}
              {{ end }}
            {{ end }}
          {{ end }}
          
          {{ if ne $inCinemas "" }}
            {{ if gt $inCinemas $now }}
              {{ if or (eq $selectedDate .String "releaseDate") (lt $inCinemas $selectedDate) }}
                {{ $releaseType = "In Cinemas" }}
                {{ $selectedDate = $inCinemas }}
              {{ end }}
            {{ end }}
          {{ end }}
          
          {{ $dateStr := $selectedDate | parseTime "RFC3339" | formatTime "Mon, 2-Jan" }}
          
            <div class="card widget-content-frame">
              <img src="{{ $coverUrl }}"
                alt="{{ $title }}"
                loading="lazy"
                style="
                  object-fit: cover;
                  border-radius: var(--border-radius) var(--border-radius) 0 0;
                  aspect-ratio: 2/3;
                "
              />
                <ul class="flex flex-column justify-evenly margin-bottom-10 margin-top-10 padding-inline-widget" style="height: 100%;">
                  <li class="text-truncate color-primary"><a href="{{ $link }}" target="_blank" style="text-decoration: none;">{{ $title }}</a></li>
                  <li class="text-truncate size-sm">{{ $releaseType }}</li>
                  <li class="text-truncate size-sm">{{ $dateStr }}</li>
                </ul>
            </div>
        {{ end }}
        
        {{/* Display series episodes */}}
        {{ range $sonarrData.JSON.Array "" | sortByTime "airDateUtc" "rfc3339" "asc" }}
          {{ $title := .String "series.title" }}
          {{ $coverUrl := printf "%s/api/v3/mediacover/%s/poster-500.jpg?apikey=%s" $sonarrUrl (.String "seriesId") $sonarrKey }}
          {{ $link := printf "%s/series/%s" $sonarrUrl (.String "series.titleSlug") }}
          {{ $date := .String "airDateUtc" | parseTime "RFC3339" }}
          {{ $seString := printf "S%02dE%02d" (.Int "seasonNumber") (.Int "episodeNumber") }}
          {{ $episodeTitle := .String "title" }}
          {{ $dateStr := $date.Format "Mon, 2-Jan 15:04" }}
          
            <div class="card widget-content-frame">
              <img src="{{ $coverUrl }}"
                alt="{{ $title }}"
                loading="lazy"
                style="
                  object-fit: cover;
                  border-radius: var(--border-radius) var(--border-radius) 0 0;
                  aspect-ratio: 2/3;
                "
              />
                <ul class="flex flex-column justify-evenly margin-bottom-10 margin-top-10 padding-inline-widget" style="height: 100%;">
                  <li class="text-truncate color-primary"><a href="{{ $link }}" target="_blank" style="text-decoration: none;">{{ $title }}</a></li>
                  <li class="text-truncate size-sm">{{ $seString }} | {{ $episodeTitle }}</li>
                  <li class="text-truncate size-sm">{{ $dateStr }}</li>
                </ul>
            </div>
        {{ end }}
      </div>
      </div>
    {{ else }}
    <div class="widget-error widget-content">
      <div class="widget-error-header">
          <div class="color-negative size-h3">ERROR</div>
          <svg class="widget-error-icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z"></path>
          </svg>
        </div>
        <p class="size-sm">Failed to fetch data.</p>
      </div>
    </div>
    {{ end }}
